### ISSUE TITLE
CMake error for SndFile

### ISSUE THREAD

**Issue by jayavanth** [facebookresearch/wav2letter#121]
```
-- Configuring done
CMake Error at CMakeLists.txt:152 (add_executable):
  Target "Decoder" links to target "SndFile::sndfile" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:141 (add_executable):
  Target "Test" links to target "SndFile::sndfile" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:130 (add_executable):
  Target "Train" links to target "SndFile::sndfile" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:99 (add_library):
  Target "wav2letter++" links to target "SndFile::sndfile" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

**Comment by jacobkahn** [comment]
@jayavanth — what is your OS/CMake version, and what command are you using to build?

**Comment by jayavanth** [comment]
OS: Ubuntu 18.04
CMake: 3.12.0

command:
```
KENLM_INC=<kenlm_inc> KENLM_ROOT_DIR=<kenlm_root>  cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF -DCMAKE_PREFIX_PATH=<arrayfire_path> -Dflashlight_DIR=<flashlight_build> -DINTEL_MKL_DIR=<mkl> -DSndFile_DIR=/home/jay/libsndfile/build
```

I built libsndfile with `cmake .. -DENABLE_PACKAGE_CONFIG=ON`

**Comment by jacobkahn** [comment]
@jayavanth — this is probably occurring because `find_package` can't find `SndFileTargets.cmake`, (which contains the `SndFile::SndFile` target) because it might not be in the right place after building SndFile. Can you try rebuilding and executing the `install` step for `SndFile` with some [`CMAKE_INSTALL_PREFIX=~/somedir`](https://cmake.org/cmake/help/v3.5/variable/CMAKE_INSTALL_PREFIX.html) (so in `libsndfile/build`, `cmake .. -DCMAKE_INSTALL_PREFIX=~/somedir`, then `make`, then `sudo make install`), then using `-DSndFile_DIR=~/somedir` when you build wav2letter++?

**Comment by jayavanth** [comment]
Thanks! It worked! Instead of using `-DSndFile_DIR=~/somedir` I added `-DCMAKE_PREFIX_PATH=~/somedir` for the wav2letter build
