### ISSUE TITLE
run time error while working on tutorials/1-librispeech_clean

### ISSUE THREAD

**Issue by tiru1930** [facebookresearch/wav2letter#123]
what():  ArrayFire Exception (Internal error:998):
In function cuda::DeviceManager::DeviceManager()
In file src/backend/cuda/platform.cpp:509
CUDA Error (35): CUDA driver version is insufficient for CUDA runtime version

In function void af::setMemStepSize(size_t)
In file src/api/cpp/device.cpp:179
Aborted (core dumped)

Do i need build arrayFire from source i have installed using 
ArrayFire-v3.6.2_Linux_x86_64.sh file

**Comment by jacobkahn** [comment]
@tiru1930 — this looks like an issue with your ArrayFire installation or your CUDA driver version (consider updating it?). Are you able to run ArrayFire's standalone tests/do they pass?

I'd recommend building ArrayFire from source from a release (e.g. [3.6.2](https://github.com/arrayfire/arrayfire/releases/tag/v3.6.2)) rather than using their installer. If you're still having trouble, consider posting an issue to ArrayFire — this isn't related to wav2letter++ as far as I can tell.
