### ISSUE TITLE
Ubuntu16.04 wav2letter compile error

### ISSUE THREAD

**Issue by AlleyEli** [facebookresearch/wav2letter#139]
I compiled and installed openmpi-4.0.0

compiled gloo source code with openmpi
use option:  -DUSE_MPI=ON and make && make install success

but wav2letter compile error:
> cmake .. -DCMAKE_BUILD_TYPE=Release -DCRITERION_BACKEND=CPU

`
/usr/local/lib/libgloo.a(context.cc.o): In function `gloo::mpi::Context::~Context() [clone .localalias.98]':
context.cc:(.text+0x1d): undefined reference to `MPI_Comm_free'
/usr/local/lib/libgloo.a(context.cc.o): In function `gloo::mpi::MPIScope::MPIScope()':
context.cc:(.text+0xe9): undefined reference to `MPI_Init'
/usr/local/lib/libgloo.a(context.cc.o): In function `gloo::mpi::MPIScope::~MPIScope()':
context.cc:(.text+0xa35): undefined reference to `MPI_Finalize'
/usr/local/lib/libgloo.a(context.cc.o): In function `gloo::mpi::Context::Context(ompi_communicator_t* const&)':
context.cc:(.text+0x116d): undefined reference to `MPI_Comm_size'
context.cc:(.text+0x118a): undefined reference to `MPI_Comm_rank'
context.cc:(.text+0x11d5): undefined reference to `MPI_Comm_dup'
/usr/local/lib/libgloo.a(context.cc.o): In function `gloo::mpi::Context::createManaged()':
context.cc:(.text+0x14ef): undefined reference to `ompi_mpi_comm_world'
/usr/local/lib/libgloo.a(context.cc.o): In function `gloo::mpi::Context::connectFullMesh(std::shared_ptr<gloo::transport::Device>&)':
context.cc:(.text+0x19d9): undefined reference to `ompi_mpi_op_max'
context.cc:(.text+0x19e7): undefined reference to `ompi_mpi_unsigned_long'
context.cc:(.text+0x19f6): undefined reference to `MPI_Allreduce'
context.cc:(.text+0x1ac6): undefined reference to `ompi_mpi_byte'
context.cc:(.text+0x1adf): undefined reference to `MPI_Allgather'
/usr/local/lib/libgloo.a(context.cc.o): In function `std::_Sp_counted_ptr_inplace<gloo::mpi::Context, std::allocator<gloo::mpi::Context>, (__gnu_cxx::_Lock_policy)2>::_M_dispose()':
context.cc:(.text._ZNSt23_Sp_counted_ptr_inplaceIN4gloo3mpi7ContextESaIS2_ELN9__gnu_cxx12_Lock_policyE2EE10_M_disposeEv[_ZNSt23_Sp_counted_ptr_inplaceIN4gloo3mpi7ContextESaIS2_ELN9__gnu_cxx12_Lock_policyE2EE10_M_disposeEv]+0x34): undefined reference to `MPI_Comm_free'
collect2: error: ld returned 1 exit status
src/tests/CMakeFiles/PreEmphasisTest.dir/build.make:1138: recipe for target 'src/tests/PreEmphasisTest' failed
make[2]: *** [src/tests/PreEmphasisTest] Error 1
CMakeFiles/Makefile2:306: recipe for target 'src/tests/CMakeFiles/PreEmphasisTest.dir/all' failed
make[1]: *** [src/tests/CMakeFiles/PreEmphasisTest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/local/lib/libgloo.a(context.cc.o): In function `gloo::mpi::Context::~Context() [clone .localalias.98]':
context.cc:(.text+0x1d): undefined reference to `MPI_Comm_free'
/usr/local/lib/libgloo.a(context.cc.o): In function `gloo::mpi::MPIScope::MPIScope()':
context.cc:(.text+0xe9): undefined reference to `MPI_Init'
....
`

**Comment by drkingman** [comment]
I had the same issue compiling on CentOS. You shall try docker install, it is rather easy.

**Comment by AlleyEli** [comment]
@drkingman  
no CPU version of the docker image
My computer doesn't support CUDA

**Comment by jacobkahn** [comment]
@AlleyEli — we've seen this issue before. I'm planning on investigating how we can make MPI linking a little more resilient soon. The fix is generally to explicitly `sudo apt-get install libopenmpi-dev`, then to rebuild/install Gloo, then rebuild wav2letter++. This worked for me recently.

**Comment by tlikhomanenko** [comment]
A docker image with CPU backend is coming (will be added during the next week).

**Comment by AlleyEli** [comment]
@drkingman  @jacobkahn  @tlikhomanenko 
thanks

**Comment by jacobkahn** [comment]
@AlleyEli — it'll be up in the next few hours.

**Comment by tlikhomanenko** [comment]
@AlleyEli Now you can use `Dockerfile-CPU` for `CPU` only build. Also the docker images are available here  https://hub.docker.com/r/wav2letter/wav2letter/tags (for both CUDA and CPU backends).

**Comment by AlleyEli** [comment]
@jacobkahn @tlikhomanenko 
Thank you very much for your kind help,

**Comment by bobblePandey** [comment]
I also faced some issue while compiling flashlight dependency. I observed that when gloo is built, the symbols in libgloo.a is not mapped from MPI even after compiling gloo with -DUSE_MPI=ON flag but those are present in libmpi.so 

$ nm /usr/local/lib/libgloo.a | grep MPI_Comm_free
                 U MPI_Comm_free

$ nm /usr/local/lib/libmpi.so | grep MPI_Comm_free
000000000006aea0 W MPI_Comm_free
000000000006b070 W MPI_Comm_free_keyval
000000000006aea0 T PMPI_Comm_free
000000000006b070 T PMPI_Comm_free_keyval

Here I can see the symbols are not linked correctly. Can anyone help with the same if it can be fixed with some code hack by linking flashlight with MPI library directly.

Above reply by @jacobkahn didn't worked for me.
https://github.com/facebookresearch/wav2letter/issues/139#issuecomment-453591033

Also I want to compile this for ARM architecture as well, that's why I'm not following the docker solution.

Thanks in Advance,
Abhishek

**Comment by jacobkahn** [comment]
@bobblePandey — can you confirm that your `libopenmpi` (or whatever lib you're using for MPI) has these missing symbols?

**Comment by bobblePandey** [comment]
@jacobkahn - Yes, the symbols are present in libmpi.so as I commented in my previous comment. I checked it using the nm command. But those are not linked to the libgloo.a due to which when I compile flashlight, the symbols are missing.
I also tried building shared library for libgloo but that also didn't worked out.

Below are the few snapshots for your reference.


**Error while compiling flashlight -------------------->**
/usr/local/lib/libgloo.a(context.cc.o): In function `gloo::mpi::Context::~Context() [clone .localalias.106]':
context.cc:(.text+0x1d): undefined reference to `MPI_Comm_free'
/usr/local/lib/libgloo.a(context.cc.o): In function `gloo::mpi::MPIScope::MPIScope()':
context.cc:(.text+0xe9): undefined reference to `MPI_Init'
/usr/local/lib/libgloo.a(context.cc.o): In function `gloo::mpi::MPIScope::~MPIScope()':
context.cc:(.text+0xc85): undefined reference to `MPI_Finalize'
/usr/local/lib/libgloo.a(context.cc.o): In function `gloo::mpi::Context::Context(ompi_communicator_t* const&)':
context.cc:(.text+0x155d): undefined reference to `MPI_Comm_size'
context.cc:(.text+0x157a): undefined reference to `MPI_Comm_rank'
context.cc:(.text+0x15c5): undefined reference to `MPI_Comm_dup'
/usr/local/lib/libgloo.a(context.cc.o): In function `gloo::mpi::Context::createManaged()':
context.cc:(.text+0x18be): undefined reference to `ompi_mpi_comm_world'
/usr/local/lib/libgloo.a(context.cc.o): In function `gloo::mpi::Context::connectFullMesh(std::shared_ptr<gloo::transport::Device>&)':
context.cc:(.text+0x1d77): undefined reference to `ompi_mpi_op_max'
context.cc:(.text+0x1d85): undefined reference to `ompi_mpi_unsigned_long'
context.cc:(.text+0x1d98): undefined reference to `MPI_Allreduce'
context.cc:(.text+0x1e68): undefined reference to `ompi_mpi_byte'


**Checking symbols in libgloo.a ------------------------------------------------------------>**
**$ nm /usr/local/lib/libgloo.a | grep ompi_mpi_op_max**
                 U ompi_mpi_op_max
**$ nm /usr/local/lib/libgloo.a | grep MPI_Comm_free**
                 U MPI_Comm_free

**Checking symbols in libmpi.so ------------------------------------------------------------>**
**$ nm /usr/local/lib/libmpi.so | grep ompi_mpi_op_max**
0000000000323b00 B ompi_mpi_op_max
0000000000306728 D ompi_mpi_op_max_addr
000000000031eb00 B ompi_mpi_op_maxloc
00000000003066d8 D ompi_mpi_op_maxloc_addr
**$ nm /usr/local/lib/libmpi.so | grep MPI_Comm_free**
000000000006aea0 W MPI_Comm_free
000000000006b070 W MPI_Comm_free_keyval
000000000006aea0 T PMPI_Comm_free
000000000006b070 T PMPI_Comm_free_keyval

**Comment by bobblePandey** [comment]
@jacobkahn Thanks for your support. I tried building all the dependencies again from scratch and was able to build the same successfully. No problems occured. I will now get back to you if I get any errors while building for ARM.

**Comment by jacobkahn** [comment]
@bobblePandey sounds good — thanks. Not quite sure what could've been going wrong there. For what it's worth: removing MPI as a dependency is something we'd like to do down the road.

**Comment by Tom-Mirowski** [comment]
Getting this issue now.

I removed the gloo directory from /flashlight/build, did a git clone of gloo, and rebuilt it, but it seems doing make always causes it to rebuild anyway.

I'm constantly getting these MPI undefined references and am unsure how to proceed

**Comment by jacobkahn** [comment]
@Tom-Mirowski — you build Gloo with the `USE_MPI=ON` option, correct?
