### ISSUE TITLE
Error: compute_ctc_loss, stat = cuda memcpy or memset failed

### ISSUE THREAD

**Issue by tzyll** [facebookresearch/wav2letter#207]
terminate called after throwing an instance of 'std::runtime_error'   what():  Error: compute_ctc_loss, stat = cuda memcpy or memset failed

With a very small Chinese data, all OK, while with 300h, it failed.
So some bad samples?
Thanks.

**Comment by tzyll** [comment]
The label length has a limitation.
In my test, it's ok if not longer than 198 including blanks.

So also https://github.com/apache/incubator-mxnet/issues/7445

**Comment by jacobkahn** [comment]
As per that issue, there may be memory limitations associated with your hardware and WarpCTC. If you have samples which you know will produce failure, you can try monitoring GPU memory usage while running to confirm.

We've decided against using cuDNN's CTC implementation both because of the variable sequence length limitation, and also because the implementation doesn't operate in `log` space, leaving it susceptible to underflow issues.
