### ISSUE TITLE
Add custom feature extraction

### ISSUE THREAD

**Issue by dambaquyen96** [facebookresearch/wav2letter#218]
Currently, i'm working on Vietnamese Speech dataset. Beside MFCC, the pitch feature is also very helpful for ASR in my language and I want to implement it.
So how can I add a custom feature extraction in wav2letter project? Is there any interface that help me to do it? And how to use it in training with flags (e.g. -mfcc, -mfsc, ...)?

**Comment by vineelpratap** [comment]
Hi, 
The feature extraction library if [here](https://github.com/facebookresearch/wav2letter/tree/master/src/feature). You would have to add a new file for pitch extraction similar to https://git.io/fhN6G which takes a vector of input and extracts the required feature. Once this is done, you can tweak https://fburl.com/vvixl2jd to make it work end to end. 

We would gladly accept a PR on this since this will be helpful for many other tasks.

**Comment by xuqiantong** [comment]
@vineelpratap I don't think you want ppl to see something through fburl =p. Here is the valid link: https://github.com/facebookresearch/wav2letter/blob/master/src/data/Featurize.cpp#L83-L97.

**Comment by dambaquyen96** [comment]
@vineelpratap @xuqiantong Thanks for your supporting ^^
