### ISSUE TITLE
Training Issue

### ISSUE THREAD

**Issue by sanakhamekhem** [facebookresearch/wav2letter#226]
I have compiled wave2letter using CPU backend, However, when I try to train the network, I have got the following error:

terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Internal error:998):
In function cuda::DeviceManager::DeviceManager()
In file src/backend/cuda/platform.cpp:509
CUDA Error (35): CUDA driver version is insufficient for CUDA runtime version

In function void af::setMemStepSize(size_t)
In file src/api/cpp/device.cpp:179
*** Aborted at 1551519955 (unix time) try "date -d @1551519955" if you are using GNU date ***
PC: @     0x7f77a2e1a428 gsignal
*** SIGABRT (@0x3ea00005e51) received by PID 24145 (TID 0x7f78232a07c0) from PID 24145; stack trace: ***
    @     0x7f77a2e1a4b0 (unknown)
    @     0x7f77a2e1a428 gsignal
    @     0x7f77a2e1c02a abort
    @     0x7f77a397f84d __gnu_cxx::__verbose_terminate_handler()
    @     0x7f77a397d6b6 (unknown)
    @     0x7f77a397d701 std::terminate()
    @     0x7f77a397d919 __cxa_throw
    @     0x7f77a5b280fd af::setMemStepSize()
    @           0x417555 main
    @     0x7f77a2e05830 __libc_start_main
    @           0x45c0d9 _start
Abandon (core dumped)

**Comment by jacobkahn** [comment]
@sanakhamekhem — to clarify, you are using the wav2letter CPU criterion backend, correct?

My guess is that you've built ArrayFire or flashlight with the CUDA backend. I'd first try running the flashlight tests. If those fail, I'd try running ArrayFire tests.

In any case, from the trace, it looks like you need to update your CUDA driver version, since you have a CUDA runtime version that is too new for it.

**Comment by umar456** [comment]
This message appears because the GPU driver is too old for the version of the CUDA Toolkit used when building ArrayFire(The official installers are built with CUDA 10.0). CUDA 10 requires 410.48 on Linux and 411.31 on Windows. You can download the latest version of the drivers at https://www.nvidia.com/Download/index.aspx?lang=en-us or through most package managers. You do not need to install the CUDA toolkit to use ArrayFire but it may be required for wave2letter.
