### ISSUE TITLE
Train error [Segmentation fault]

### ISSUE THREAD

**Issue by RechardWong** [facebookresearch/wav2letter#310]
I new this Issues because  I can't reopen #308.
I git pull the fixed code 7f26987 and re-build it.
then I run ` build/Train  train --flagsfile tutorials/1-librispeech_clean/train.cfg`
it seems everything ok in the beginning，but after the program has been running for a while，I get this error：
```
*** Aborted at 1559007036 (unix time) try "date -d @1559007036" if you are using GNU date ***
PC: @     0x7f55192ee460 (unknown)
*** SIGSEGV (@0x0) received by PID 33419 (TID 0x7f5585428e00) from PID 0; stack trace: ***
    @     0x7f55191b54b0 (unknown)
    @     0x7f55192ee460 (unknown)
    @           0x561093 w2l::tknIdx2Ltr()
    @           0x563bed w2l::tknPrediction2Ltr()
    @           0x478767 _ZZ4mainENKUlRKN2af5arrayES2_RN3w2l13DatasetMetersEE1_clES2_S2_S5_
    @           0x47b868 _ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_IN3w2l17SequenceCriterionEES_INS3_10W2lDatasetEES_INS0_19FirstOrderOptimizerEES9_ddbiE3_clES2_S5_S7_S9_S9_ddbi.constprop.11263
    @           0x41b193 main
    @     0x7f55191a0830 __libc_start_main
    @           0x476959 _start
Segmentation fault (core dumped)

```

**Comment by SYnchronYSe** [comment]
I'm getting the exact same error. I'm training on CPU backend, and all my make-tests except the ones not supported on CPU backend passed.

I disabled the features not supported on CPU backend as suggested by @jacobkahn in #309

**Comment by RechardWong** [comment]
> I'm getting the exact same error. I'm training on CPU backend, and all my make-tests except the ones not supported on CPU backend passed.
> 
> I disabled the features not supported on CPU backend as suggested by @jacobkahn in #309
I have seen your posted issues,and I think my error seems to be different from yours.
Actually，I'm training on GPU backend.

**Comment by SYnchronYSe** [comment]
Hi @RechardWong ,
I rebuilt on CUDA backend and got the exact same error after about 8 minutes of 1st iteration.
I'm using GeForce GT710 with 2GB memory.

Maybe the dataset is too large for the system to handle, since my cpu usage was going 100%, as you can see:
![image](https://user-images.githubusercontent.com/30228260/58780628-24a94480-85f7-11e9-8b84-79e0bd49ef00.png)


Maybe we should try with a smaller dataset and see if the same happens.

**Comment by SYnchronYSe** [comment]
All my wav2letter tests passed.

My AllReduce test of Flashlight was failing, but that shouldn't be an issue as I ran the training after disabling it, as suggested in #309

**Comment by SYnchronYSe** [comment]
I tried with just 100 samples of data and 5 iterations. It succeded in 6 minutes.
I can't run in parallel since I have disabled AllReduce. That's why it's taking really long.
Conclusion is that the dataset is too much for the system to handle.

You can first try running on parallel threads using mpirun command, if it doesn't work, try with reduced dataset.

**Comment by RechardWong** [comment]
All my wav2letter tests and flashlight tests passed,you can see some detail info from  here #308 . 
I  got above errors with the instruction of `tutorials\1-librispeech_clean`，but I trained successfully with `recipes\librispeech`.

**Comment by jacobkahn** [comment]
@SYnchronYSe — you can't parallelize training any more than you are now unless you have multiple GPUs. See the [flashlight distributed training docs](https://fl.readthedocs.io/en/latest/distributed.html).
