### ISSUE TITLE
seq2seq decoder  drops words at the end 

### ISSUE THREAD

**Issue by goodmajia** [facebookresearch/wav2letter#348]
I use s2s decoder for chinese model, but I find words will be dropped at the end of sentence,  as follows:

```
[sample: BAC009S0764W0418, WER: 41.6667%, LER: 43.4783%, slice WER: 51.3049%, slice LER: 51.1552%, progress: 94.8%]
[WARNING] No completed candidates.
|T|: 而 阿 拉 木 图 仅 为 四 百 亿 美 元
|P|: 而 阿 拉 木 图 仅 为
|t|: 而 | 阿 | 拉 | 木 | 图 | 仅 | 为 | 四 | 百 | 亿 | 美 | 元
|p|: 而 | 阿 | 拉 | 木 | 图 | 仅 | 为

[sample: BAC009S0764W0403, WER: 41.6667%, LER: 43.4783%, slice WER: 51.288%, slice LER: 51.1419%, progress: 95%]
[WARNING] No completed candidates.
|T|: 许 玮 甯 最 近 到 法 国 工 作
|P|: 徐 伟 宁 最 近 到 法
|t|: 许 | 玮 | 甯 | 最 | 近 | 到 | 法 | 国 | 工 | 作
|p|: 徐 | 伟 | 宁 | 最 | 近 | 到 | 法

[sample: BAC009S0764W0413, WER: 60%, LER: 47.3684%, slice WER: 51.3007%, slice LER: 51.1365%, progress: 95.2%]
[WARNING] No completed candidates.
|T|: 有 利 于 降 低 公 司 运 营 成 本
|P|: 有 利 于 降 低 公 司
|t|: 有 | 利 | 于 | 降 | 低 | 公 | 司 | 运 | 营 | 成 | 本
|p|: 有 | 利 | 于 | 降 | 低 | 公 | 司

[sample: BAC009S0764W0328, WER: 36.3636%, LER: 38.0952%, slice WER: 51.2768%, slice LER: 51.116%, progress: 95.4%]
[WARNING] No completed candidates.
|T|: 在 二 零 二 二 年 冬 季 奥 运 会 的 竞 选 当 中
|P|: 在 二 零 二 二 年 冬 季 奥
|t|: 在 | 二 | 零 | 二 | 二 | 年 | 冬 | 季 | 奥 | 运 | 会 | 的 | 竞 | 选 | 当 | 中
|p|: 在 | 二 | 零 | 二 | 二 | 年 | 冬 | 季 | 奥
```

the decoder cfg i used as follows:

```
-decodertype tkn \
-lm lm_path \
-am am_path \
-test test_path \
-silweight 0 -maxdecoderoutputlen 520 -maxload -1 -nthread 1 -nthread_decoder 1 -smearing max -show -showletters \
-beamsize 80 -beamthreshold 7 -lmweight 1.2 -wordscore 2.0 -smoothingtemperature 1.0 \
-hardselection 1.5 -softselection 10.0 -attentionthreshold 30 -minloglevel 0 -logtostderr true -reportiters 1 \
-sclite log
```

what's the possible reason for this?  is anything wrong for my decoder cfg?

**Comment by xuqiantong** [comment]
This is the notorious *early stopping* problem in seq2seq decoder. If you have checked the viterbi transcriptions (the one from the test.cpp), and they do not stop as early as those samples you listed here, I would suggest to try to decrease `-hardselection` first. 

Your results looks promising already, I think you should also try to tune these parameters as well:
- `attentionthreshold`
- `lmweight`
- `wordscore`
Details of them are described in https://arxiv.org/abs/1904.02619.

Since seq2seq decoder is lexicon-free and you treat each Chinese character itself as a word, I think you can get rid off the `|` after each word, so that *letter* = *word* and *WER* = *LER*.

**Comment by goodmajia** [comment]
@xuqiantong  thanks , I decrease `-hardselection` ,but this problem still exists! I will take a look at the source code of Test.cpp.
