### ISSUE TITLE
multi CPU decode

### ISSUE THREAD

**Issue by gloryyingling** [facebookresearch/wav2letter#358]
Is there any way to utilize decoder to use multi CPU so that we can save inference time.

**Comment by dhruv-karan** [comment]
plz reply me me on dhruvkaran243@gmail.com need u r help on speech2text

**Comment by tlikhomanenko** [comment]
Hi @gloryyingling,

You could use `--nthread_decoder 6` to set the cpu threads to 6 to run Decode.cpp.

**Comment by xuqiantong** [comment]
@gloryyingling As @tlikhomanenko said, you can split the whole dataset into several partitions and decode each part on a single CPU by specifying `--nthread_decoder`. However, if you are asking about decoding a single sample with multiple threads/CPU, we do support that and will probably not do it in the short future, since our decoder is quite efficient already.
