### ISSUE TITLE
unknown token issue

### ISSUE THREAD

**Issue by YuBeomGon** [facebookresearch/wav2letter#363]
during decoding, 

Skipping unknown token: semon's
Skipping unknown token: battleax
Skipping unknown token: andella
Skipping unknown token: andella
Skipping unknown token: kaffar's
Skipping unknown token: thel
...

what is it and is it ok??

**Comment by xuqiantong** [comment]
I believe you provided a lexicon to the decoder, so that one of the lexicon decoders is selected here. `Skipping unknown token: [token]` usually means the `[token]` appears in the target/reference but not in the lexicon. It is OK, but those unknown tokens will be represented as `<unk>` in the final reference.
