### ISSUE TITLE
Using pretrained models in the lua version of Wav2letter

### ISSUE THREAD

**Issue by rdoshi96** [facebookresearch/wav2letter#381]
I want to load the pretrained model from the paper Sequence-to-Sequence Speech Recognition with Time-Depth Separable Convolutions (Hannun et al., 2019). Is it possible to do this with the lua implementation of wav2letter?

**Comment by jacobkahn** [comment]
@rdoshi96 — this isn't supported natively, since the implementation of the underlying tensor libraries is different. If you were to reimplement the TDS block in Lua, it wouldn't be too challenging to write a script to convert those weights, but we have no plans to add anything like this since the Lua version is unsupported.
