### ISSUE TITLE
ASG transitions

### ISSUE THREAD

**Issue by lunixbochs** [facebookresearch/wav2letter#382]
Are ASG transitions effectively bigram probabilities of each letter pair in your input corpus, weighted against “how long each letter is likely to self repeat”?

If so, why bother training the bigram probabilities at all, since we can calculate them from the training set? Why not then just train the self-repeat-weights directly as a separate score, which can even be more intelligent than a single number (like a curve)? I’m wondering if combining these both into a single transitions matrix makes it worse at both jobs.

**Comment by jcai1** [comment]
Hi lunixbochs,

Yes, ASG transitions are basically just bigram probabilities as you describe. We use a transitions matrix because it is simple to implement. Your proposal to separately track bigram probabilities & self-repeat probabilities is interesting. Pre-training bigram probabilities using the training set (or even a larger text corpus) is an option that we've discussed since one of ASG's main weaknesses is the difficulty of initializing its transitions. We could try something like this in the future.
