### ISSUE TITLE
Skipping unknown token '—' when falling back to letter target for the unknown word: —

### ISSUE THREAD

**Issue by xtluo-ai** [facebookresearch/wav2letter#414]
Hi, I'm trying to use this toolkit for E2E ASR on Chinese, However, after data preparation, I keep getting warnings/errors like:

```
Skipping unknown token '—' when falling back to letter target for the unknown word: —
Skipping unknown token '.' when falling back to letter target for the unknown word: .
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Unknown entry in dictionary: '_'
```

I'm confused because none of those characters above exist in my files.

---
- files I created at the data preparation stage
```
# /prj/data/
lexicon.txt  lm.kenlm  network.arch  tokens.txt  train.lst  valid.lst
```

- content in each file

```shell
# lexicon.txt
一尺 Y IY4 CH IY3
一尾 Y IY4 W EY3
一局 Y IY4 J UW2
...
```

```shell
# tokens.txt
Y
IY4
CH
IY3
...
```

```shell
# train.lst & valid.lst
0001 /datasets/0001.wav 3.35 一层
```

``` shell
# train.cfg
# Training config for Librispeech using Time-Depth Separable Convolutions
# Replace `[...]`, `[MODEL_DST]`, `[DATA_DST]` with appropriate paths
--runname=seq2seq_tds_distributed
--rundir=/prj/data
--tokensdir=/prj/data
--archdir=/prj/data
--train=/prj/data/train.lst
--valid=/prj/data/valid.lst
--lexicon=/prj/data/lexicon.txt
--arch=network.arch
--tokens=tokens.txt
--criterion=seq2seq
--lr=0.05
--lrcrit=0.05
--momentum=0.0
--stepsize=40
--gamma=0.5
--maxgradnorm=15
--mfsc=true
--dataorder=output_spiral
--inputbinsize=25
--filterbanks=80
--attention=keyvalue
--encoderdim=512
--attnWindow=softPretrain
--softwstd=4
--trainWithWindow=true
--pretrainWindow=3
--maxdecoderoutputlen=120
--usewordpiece=true
--wordseparator=_
--sampletarget=0.01
--target=ltr
--batchsize=4
--labelsmooth=0.05
--nthread=4
--memstepsize=4194304
--eostoken=true
--pcttraineval=1
--pctteacherforcing=99
--iter=200
--enable_distributed=true
```

what did I miss? thanks.

---
### Update 1

There are some errors in the above files:
- `tokens` should be the unique characters of all text?
```shell
# tokens.txt
|
一
尺
尾
局
```
---
### Update 2

- `lexicons` should be graphemes lexicon in this case:
```shell
# lexicon.txt
一尺 一 尺 |
一尾 一 尾 |
一局 一 局 |
```

**Comment by tlikhomanenko** [comment]
Hi @xtluo-ai,



> * `tokens` should be the unique characters of all text?

Tokens could be letterы, word-pieces, words itself. This is the thing for which your acoustic model will return prediction. For English in case of letters tokens we will have
```
a
b
c
...
```
for word pieces for example
```
a
...
z
to
ma
...
nig
...
```

> * `lexicons` should be graphemes lexicon in this case:

Lexicon is the mapping between words and sequence of your tokens, so it should be sequence of things from the tokens set ending with the silence token to predict also the space between words. For example (for English) in case of letters tokens lexicon looks like:
```
apple a p p l e |
```
for word-pieces:
```
apple ap ple |
```

> Hi, I'm trying to use this toolkit for E2E ASR on Chinese, However, after data preparation, I keep getting warnings/errors like:
> 
> ```
> Skipping unknown token '—' when falling back to letter target for the unknown word: —
> Skipping unknown token '.' when falling back to letter target for the unknown word: .
> terminate called after throwing an instance of 'std::invalid_argument'
>   what():  Unknown entry in dictionary: '_'
> ```
> 
> I'm confused because none of those characters above exist in my files.

The problem here that you have some words in your train/valid lists which are not defined in the lexicon file. That is why to create the spelling for them letters sequence is generated where the word "一尺" is represented as "一 尺", but "一" is absent in your token set. Solution is to make sure that each word from the lists files in the transcriptions is presented in the lexicon.

**Comment by xtluo-ai** [comment]
Thanks, @tlikhomanenko , I figured it out and get everything working...
