### ISSUE TITLE
Missing decode.cfg for Timit dataset

### ISSUE THREAD

**Issue by Zephyrasgit** [facebookresearch/wav2letter#468]
Hi, we have tried and succeeded in training and subsequently decoding our own trained model using the LibriSpeech dataset. However, while trying again on the Timit dataset, we failed to do so as the decode.cfg file is missing at the path "wav2letter/recipes/timit/configs/conv_relu/".

If the file was removed on purpose, can anyone enlighten us if there is a guide on how we can write this config file on our own?

**Comment by tlikhomanenko** [comment]
Hi @Zephyrasgit,

In the paper where this model was used only Viterbi path (greedy best path) was used to compute PER (so no external language model). We reorganized a bit the timit recipe: data here https://github.com/facebookresearch/wav2letter/tree/master/recipes/data/timit and model is here now https://github.com/facebookresearch/wav2letter/tree/master/recipes/models/learnable_frontend.

To use beam-search decoder you can have a look at config in other recipes, for example https://github.com/facebookresearch/wav2letter/blob/master/recipes/models/conv_glu/librispeech. 

If you want to use ZeroLM then just put `--lm=''`, in case of kenlm language model you need to train kenlm model, for example on the timit transcriptions, and use it during decoding. In both cases you need also to prepare lexicon file: mapping of words into phonemes sequence. You have no any word separator so use `--wordseparator=''` and in the lexicon for each word put only sequence of phonemes.

**Comment by Zephyrasgit** [comment]
Thank you for taking time to reply us on our issues.

We note from your reply that there is some engineering effort required on our part to create some of the files, such as the decoder.

> In both cases you need also to prepare lexicon file: mapping of words into phonemes sequence.

On the lexicon file, can we kindly ask how should we go about preparing this file? Is this another open sourced program that we can tap on, or does your repository provide codes for us to prepare this lexicon file? We currently have tried using the Librispeech lexicon file to decode TIMIT test files, but errors such as `what(): Unknown entry in dictionary: 'a'` will be thrown.

> You have no any word separator so use `--wordseparator=''` and in the lexicon for each word put only sequence of phonemes.

On this word separator, we have tried your method but errors such as `what(): Unknown entry in dictionary: ''` will be thrown, similar to the above.

Do you have any workarounds to these issues/obstacles?

**Comment by avidov** [comment]
Are you working on training or inference ?
In either case wav2letter has all the data that you need either ready on AWS S3 or has preparation scripts.
For inference see
https://github.com/facebookresearch/wav2letter/wiki/Inference-Run-Examples

All the model files are at AWS S# bucket:
http://dl.fbaipublicfiles.com/wav2letter/inference/examples/model




On Jan 15, 2020, at 1:37 AM, Zephyrasgit <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you for taking time to reply us on our issues.

We note from your reply that there is some engineering effort required on our part to create some of the files, such as the decoder.

In both cases you need also to prepare lexicon file: mapping of words into phonemes sequence.

On the lexicon file, can we kindly ask how should we go about preparing this file? Is this another open sourced program that we can tap on, or does your repository provide codes for us to prepare this lexicon file? We currently have tried using the Librispeech lexicon file to decode TIMIT test files, but errors such as what(): Unknown entry in dictionary: 'a' will be thrown.

You have no any word separator so use --wordseparator='' and in the lexicon for each word put only sequence of phonemes.

On this word separator, we have tried your method but errors such as what(): Unknown entry in dictionary: '' will be thrown, similar to the above.

Do you have any workarounds to these issues/obstacles?

**Comment by tlikhomanenko** [comment]
@Zephyrasgit,

First of all, with what config did you train acoustic model for Timit? What is the token set you used for Timit dataset? The second question: do you want to decode with some language model?

**Comment by Zephyrasgit** [comment]
Thank you @tlikhomanenko @avidov  for your replies.

@avidov We have worked on training, but to no avail, so we are trying inference now. We have followed the inference guide using the link you provided. After downloading the pre-trained model files from AWS S3 bucket, we encountered this error (enclosed in ###'s) while doing inference with `simple_streaming_asr_example`:

###############
Started features model file loading ... 
Completed features model file loading elapsed time=85953 microseconds

Started acoustic model file loading ... 
terminate called after throwing an instance of 'std::invalid_argument'
  what():  TDSBlock::TDSBlock() is called with null conv.
Aborted (core dumped)
###############

Here, I omitted the full command but we made sure our path to the input wav file to be transcribed, the path to `simple_streaming_asr_example`, and the path to base input files where the models exist were all correct. We also made sure to clone the most recent master of all repositories required (KenLM, wav2letter). At first glance, we suspect it was an issue with `simple_streaming_asr_example` trying to open and load `acoustic_model.bin`. Do you know what is the issue here?

@tlikhomanenko Our answer to first question: We used the default config file given in [https://github.com/facebookresearch/wav2letter/blob/master/recipes/models/learnable_frontend/train_baseline_conv_relu.cfg](url). We used `prepare.py` in [https://github.com/facebookresearch/wav2letter/blob/master/recipes/models/learnable_frontend/prepare.py](url) to generate our tokens. 

Our answer to second question: We attempted the training with no language model, but to no avail.

**Comment by avidov** [comment]
Hi,

Sorry about the inference issues. I just uploaded a fix and an updated model.
Please obtain both.

To update the code:
> cd wav2letter
> git pull

To update the model:
Use the

for f in acoustic_model.bin arch.txt decoder_options.json feature_extractor.bin language_model.bin lexicon.txt tokens.txt ; do wget http://dl.fbaipublicfiles.com/wav2letter/inference/examples/model/${f} ; done


command

Please let me know if you still have any issues



On Jan 16, 2020, at 1:24 AM, Zephyrasgit <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you @tlikhomanenko<https://github.com/tlikhomanenko> @avidov<https://github.com/avidov> for your replies.

@avidov<https://github.com/avidov> We have worked on training, but to no avail, so we are trying inference now. We have followed the inference guide using the link you provided. After downloading the pre-trained model files from AWS S3 bucket, we encountered this error (enclosed in ###'s) while doing inference with simple_streaming_asr_example:

###############
Started features model file loading ...
Completed features model file loading elapsed time=85953 microseconds

Started acoustic model file loading ...
terminate called after throwing an instance of 'std::invalid_argument'
what(): TDSBlock::TDSBlock() is called with null conv.
Aborted (core dumped)
###############

Here, I omitted the full command but we made sure our path to the input wav file to be transcribed, the path to simple_streaming_asr_example, and the path to base input files where the models exist were all correct. We also made sure to clone the most recent master of all repositories required (KenLM, wav2letter). At first glance, we suspect it was an issue with simple_streaming_asr_example trying to open and load acoustic_model.bin. Do you know what is the issue here?

@tlikhomanenko<https://github.com/tlikhomanenko> Our answer to first question: We used the default config file given in https://github.com/facebookresearch/wav2letter/blob/master/recipes/models/learnable_frontend/train_baseline_conv_relu.cfg<x-msg://6/url>. We used prepare.py in https://github.com/facebookresearch/wav2letter/blob/master/recipes/models/learnable_frontend/prepare.py<x-msg://6/url> to generate our tokens.

Our answer to second question: We attempted the training with no language model, but to no avail.

**Comment by Zephyrasgit** [comment]
Thank you for your reply @avidov.

We are extremely delighted to inform that we are able to do inference after your fix. Thank you for you and your colleagues' (if any) work to fix the issue!

I will be closing this issue since we were able to achieve (albeit partially, since our task changed from training to inference) what we required for our work. Thank you!
