### ISSUE TITLE
Dealing with punctuation

### ISSUE THREAD

**Issue by cri5Castro** [facebookresearch/wav2letter#492]
Hello,there I wanted to know if the library perfom some kind of preprocessing with punctuation, or should it be made before by the user, I mean the transcriptions are splited by tokens only by space or are punctuation separed from the tokens

**Comment by tlikhomanenko** [comment]
Hi @cri5Castro,

We don't do any preprocessing inside w2l. During train/test time you are providing the list file where transcription for each audio file is specified. Here transcription could contain punctuation. Also you provide the lexicon how to map words (we split transcription by space to extract words) to their sequence of tokens (acoustic model will learn distribution over this tokens set). So here you can define your own mapping to map "world," -> "w o r l d |" to have training without punctuation token or to "w o r l d , | " if you added "," to the tokens set. 

So the lexicon could help you to do anything you need.

The only thing to be care then is Viterbi and decoding WER/LER computation. We look at the transcription you provide in the list file and compare words/sequence of letters generated by the model with them, so if you have punctuation in the list file but train without punctuation then WER/LER will be higher because all mistakes for punctuation will be accounted.
