### ISSUE TITLE
Lexicon for AM training 

### ISSUE THREAD

**Issue by cri5Castro** [facebookresearch/wav2letter#497]
Hello I wanted to know if the  lexicon for AM training should be composed only by the training data or should it contain also the dev data, also I want to know the same for  the decoder lexicon
 thanks in advance

**Comment by tlikhomanenko** [comment]
@cri5Castro,

For AM training there are options (but in any case this just influences how the Viterbi WER will be computed and looking at this WER you pick the best snapshot):
- if you train with letters tokens lexicon can be train+dev words (no any problems with this), because you always know a rule how to map a word into letters. 
- if you train with word-pieces then better to use only training data lexicon to prevent overfitting to the words in the dev which are absent in the train and for which we don't know (actually we still have the model to map to word-pieces any word, but we don't want to overfit) the mapping into word-pieces. 

In both cases this is more question of model selection because the lexicon without dev just influence on Viterbi WER (as soon as we will have errors on unk words in this case).

About beam-search decoding: better to construct lexicon from the LM training data, or LM training data + train transcriptions, or just train transcriptions. In all case pick the top-k words by their occurrence. No any dev, because you do optimization of beam-search decoder parameters on dev and you are trying simulate situation like with test for which you don't know all words. If you will use dev in lexicon then you will definitely overfit in beam-search decoding.
