### ISSUE TITLE
Error while trying to evaluate char model ppl

### ISSUE THREAD

**Issue by cri5Castro** [facebookresearch/wav2letter#534]
hi i'm trying to evaluate a  char Conv lm trained on fairseq ,  I use the same arch that the 14b model unfortunatly i'm having this error while trying to evaluate the model 

```
  File "wav2letter/recipes/models/lexicon_free/utilities/compute_upper_ppl_convlm.py", line 196, in <module>
    model, input_data, indices_token_dict, token_indices_dict, known_words
  File "wav2letter/recipes/models/lexicon_free/utilities/compute_upper_ppl_convlm.py", line 93, in compute_ppl_upper_limit_char_convlm
    assert numpy.allclose(sum_logp, sum_logp_known + sum_logp_unknown), "Error in loss"
```

**Comment by tlikhomanenko** [comment]
Hi @cri5Castro,

I am computing in the script total loss in two ways: one is standard (for all words) and the second one separately on known words (which are in vocab) and on unknown words (out of vocab), so they should be the same because you just disjoint to compute two parts. 

First thing to try - can you change "Error in loss" -> "Error in loss {} {} {} {}".format(sum_logp, sum_logp_known + sum_logp_unknown, sum_logp_known, sum_logp_unknown) to see what exactly the difference?

Can you check if this happens on one sentence only (not for the full text)?

**Comment by tlikhomanenko** [comment]
@cri5Castro, any update here?

**Comment by tlikhomanenko** [comment]
Feel free to reopen if you want to discuss again!
