### ISSUE TITLE
training process, cuda out of memory?

### ISSUE THREAD

**Issue by bolt163** [facebookresearch/wav2letter#54]
(root) @gpucommtest1:~>  luajit ~/wav2letter/train.lua --train -rundir ~/experiments -runname hello_librispeech -arch ~/wav2letter/arch/librispeech-glu-highdropout -lr 0.1 -lrcrit 0.0005 -pu 1 -linseg 1 -linlr 0 -linlrcrit 0.005 -onorm target -nthread 6 -dictdir ~/librispeech-proc  -datadir ~/librispeech-proc -train train-clean-100+train-clean-360+train-other-500 -valid dev-clean+dev-other -test test-clean+test-other -gpu 1 -sqnorm -mfsc -melfloor 1 -surround "|" -replabel 2 -progress -wnorm -normclamp 0.2 -momentum 0.9 -weightdecay 1e-05
| experiment path: /data1/experiments/hello_librispeech
| experiment runidx: 1
| number of classes (network) = 30
[Network spec]
C NCHANNEL 400 13 1
GLU
DO 0.2
C 200 440 14 1
GLU
DO 0.214
C 220 484 15 1
GLU
DO 0.22898
C 242 532 16 1
GLU
DO 0.2450086
C 266 584 17 1
GLU
DO 0.262159202
C 292 642 18 1
GLU
DO 0.28051034614
C 321 706 19 1
GLU
DO 0.30014607037
C 353 776 20 1
GLU
DO 0.321156295296
C 388 852 21 1
GLU
DO 0.343637235966
C 426 936 22 1
GLU
DO 0.367691842484
C 468 1028 23 1
GLU
DO 0.393430271458
C 514 1130 24 1
GLU
DO 0.42097039046
C 565 1242 25 1
GLU
DO 0.450438317792
C 621 1366 26 1
GLU
DO 0.481969000038
C 683 1502 27 1
GLU
DO 0.51570683004
C 751 1652 28 1
GLU
DO 0.551806308143
C 826 1816 29 1
GLU
DO 0.590432749713
C 908 1816 1 1
GLU
DO 0.590432749713
C 908 NLABEL 1 1

THCudaCheck FAIL file=/data1/torch/extra/cutorch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
luajit: /data1/torch/install/share/lua/5.1/nn/utils.lua:11: cuda runtime error (2) : out of memory at /data1/torch/extra/cutorch/lib/THC/generic/THCStorage.cu:66
stack traceback:
	[C]: in function 'resize'
	/data1/torch/install/share/lua/5.1/nn/utils.lua:11: in function 'torch_Storage_type'
	/data1/torch/install/share/lua/5.1/nn/utils.lua:57: in function 'recursiveType'
	/data1/torch/install/share/lua/5.1/nn/Module.lua:160: in function 'f'
	...ch/install/share/lua/5.1/wav2letter/runtime/netutils.lua:26: in function 'TemporalConvolution'
	...ch/install/share/lua/5.1/wav2letter/runtime/netutils.lua:213: in function 'create'
	/data1/wav2letter/train.lua:368: in main chunk
	[C]: at 0x004064f0

**Comment by vineelpratap** [comment]
Hi, looks like your GPU memory was not enough to train the model. This is mostly because of model params are too high for the GPU as it is failing in the network initialization stage itself. If you just want to play around with wav2letter on your GPU, you can try a smaller architecture by removing some layers/reducing nodes at layers in https://github.com/facebookresearch/wav2letter/blob/master/arch/librispeech-glu-highdropout . Do make sure the number of input nodes which feed to next layer are valid.

Also FWIW, there are some params which can sample the training dataset helps - https://github.com/facebookresearch/wav2letter/blob/master/train.lua#L73-L75 .

**Comment by ambigus9** [comment]
@vineelpratap I'm getting error: "No algorithms found that would fit in free GPU memory"

![imagen](https://user-images.githubusercontent.com/16579856/43658076-655fb6f4-971d-11e8-9cfe-7c2e4c160f2f.png)

What should I do?
Thanks.
