### ISSUE TITLE
About CTC VAD

### ISSUE THREAD

**Issue by heibaidaolx123** [facebookresearch/wav2letter#567]
In VoiceActivityDetection-CTC, the blank label is used as silence.
From my understanding, blank is not trained as silence, and it's used in CTC as a placeholder.
For a audio with transcription AB, (no silence between A and B), the best path from greedy decoding with a CTC model may be A _ _ _ B _ _ _( _ for blank), in this case, it's wrong if blank is used as silence.
Any ideas?
Thanks.

**Comment by jacobkahn** [comment]
@heibaidaolx123 — the blank is used both as silence as a placeholder in CTC at training time. When there is silence between words, since CTC is evaluated over the entire utterance at a time, it will output the blank token when computing path probabilities through the graph. It's possible the blank token is also output between words as well, but after the probabilities are computed, the rest of the VAD procedure looks for clusters of silence tokens that are of a certain size to denote breaks between words that are suitable for separation.
