### ISSUE TITLE
How to fully utilize CPU and GPU in Decoder?

### ISSUE THREAD

**Issue by xubuild** [facebookresearch/wav2letter#618]
Hi, I am using the STOA 2019 pre-trained model (Seq2Seq Transformer) and Decoder to recognize a large data set. The server is 36 core CPU and 8 GPU. I have tried modifying the following parameters as described in the WIKI, but the utilization is still quite low.
`--nthread=32; --nthread_decoder=8; --nthread_decoder_am_forward=8 `
I wonder how can I utilize more CPU and GPU, so I can get better speed? Thanks!

**Comment by tlikhomanenko** [comment]
Hi @xubuild,

Because this is seq2seq model attention is used during decoder step, that is why each decoder thread is working on GPU too (so you cannot use more CPU here with current implementation). Maximum threads you can use for decoding is 8 here which you already set. You can improve the utilization of GPU only decreasing the `beamsize`, `beamsizetoken`, `beamthreshold` (which can hurt of course the final quality) which speedup CPU computation and thus GPU utilization could be a bit better.
