### ISSUE TITLE
GPU GEMM backend for inference

### ISSUE THREAD

**Issue by abdul-0** [facebookresearch/wav2letter#651]
I looked at the inference source and found out that fbgemm is used for nn backend which only supports CPU with AVX2 I think, so I would like to know was it preferred over GPU for any reason? what advantage or disadvantage there would be in case of implementing GPU based GEMM backend? I don't have AVX2 support in CPU(there is an opened issue related to it [illegal instruction](https://github.com/facebookresearch/wav2letter/issues/604)). So upgrading a CPU with AVX2 is one option and getting GPUs is another but don't want to do both. So, which option would be best for most performance gain?

Thanks.

**Comment by padentomasello** [comment]
Hi @abdul-0, thanks for your comments. Our first priority when building the inference pipeline was to allow users who do not have a GPU to run streaming inference using our models. 

It is totally feasible to build a GPU based inference backend, and it's something we've discussed, but it is not in our short-term roadmap. (It shouldn't be too difficult if you want to give it a look!). 

> So upgrading a CPU with AVX2 is one option and getting GPUs is another but don't want to do both. So, which option would be best for most performance gain?

This is hard to answer, because it really depends on what you are looking to do. If you are strictly concerned about running streaming models using our inference platform, upgrading to a CPU with AVX2 might be the best approach. The inference speed would not be as fast as it could be, however if we were to build a GPU backend for inference. You would also not be able to train models.

**Comment by abdul-0** [comment]
Hi @padentomasello thanks for the insights.

> If you are strictly concerned about running streaming models using our inference platform, upgrading to a CPU with AVX2 might be the best approach.

if you think that training of streaming models is not going to be difficult and I won't miss anything which is offered in your existing streaming models/inference platform, I would like to give GPU GEMM a try.

> however if we were to build a GPU backend for inference. You would also not be able to train models.

Could you please elaborate why that would be an issue with GPU backend?

**Comment by lunixbochs** [comment]
You didn't quote enough.

> upgrading to a CPU with AVX2 might be the best approach.
> The inference speed would not be as fast as it could be
> You would also not be able to train models

**Comment by padentomasello** [comment]
Hi @abdul-0, sorry if I was unclear. Yes, I meant you would not be able to train models if you did not have a GPU. (We actually do support it technically, but training on a CPU is prohibitively slow, so I would not recommend it). 

If you are going to try to build streaming inference using the GPU, I'd encourage you to checkout https://github.com/facebookresearch/wav2letter/wiki/Inference-Framework.

I'll close this issue for now.

**Comment by vchagari** [comment]
Hi @padentomasello and @lunixbochs 
Could you guys able to add CUDA/GPU Backend support for Streaming convnets Streaming Inference use case?.
