### ISSUE TITLE
Differences libri-100 and libri-1K

### ISSUE THREAD

**Issue by AlexandderGorodetski** [facebookresearch/wav2letter#690]
Hello,

When I look on libri-100 and libri-1K examples I see difference in the format of duration in .lst files.

In the case of libri-100 I see that a duration is in seconds.

In the case of libri-1K I see that a duration in in mili seconds.

What is the most updated format? (Is this number in use or do you extract length of an utterance from the flac file?)

Thanks,
Alexander.

**Comment by avidov** [comment]
The format uses milliseconds. See:
https://github.com/facebookresearch/wav2letter/blob/96b0c074870fb8ce9b96f7e7bd9e6a2080988e66/src/data/W2lListFilesDataset.cpp#L123
calling:
https://github.com/facebookresearch/wav2letter/blob/20388694f596b3ccb015479b9a3042a34dba34fd/src/data/Utils.h#L23

**Comment by vineelpratap** [comment]
We use the duration column for two things
1. Sorting the samples so that we can batch similar length samples together
2. filtering for `--minisz` and `--maxisz`

So, as long you are consistent during your training, it doesn't matter. We have been using  `msec` for most of the recipes. ` libri-100`  seems to be an exception and we will try to fix it.
