### ISSUE TITLE
momentum setting when train streaming conv net make size model is double?

### ISSUE THREAD

**Issue by mlexplore1122** [facebookresearch/wav2letter#774]
### Question
I have trained model with streaming conv net setting with librispeech, with default setting 
- momentum = 0, size model is: 460479241 b ~ 439 Mb
- momentum !=0, size model is: 920933503 b ~ 878 Mb.
And I think because model save state of optimize with momentum, but size model double is not normal, is it?
size model will make my problem when want to use streaming model with option on device?, so what can i do, or when i convert streaming model with tools in streaming, the addition info about optimizer in model will be removed. 
Thanks you

**Comment by tlikhomanenko** [comment]
The model size is doubled because we save optimizer and in case of momentum for each model parameter we store velocities in the optimizer. During model converting for streaming inference we don't use optimizer (we don't need it), so you will have 439 Mb as model 

cc @vineelpratap to confirm not saving optimizer for inference.
