### ISSUE TITLE
mobile backend

### ISSUE THREAD

**Issue by bill-kalog** [facebookresearch/wav2letter#818]
### Question
Hi, is it still in your plans to release a backend that will work on mobile devices?
If not, could you share any pointers as to how to do it? Do you have to create something similar
to `fbgemm` but for `QNNPACK` or did you follow some other approach?

**Comment by vineelpratap** [comment]
Hi, we have not working on mobile backend at the moment and it is not in our near future plans. 

For extending to mobile, one would have to remove the dependency on `fbgemm` and use a different backend which supports fp16 operations like [xnnpack](https://github.com/google/XNNPACK) or [Accelerate](https://developer.apple.com/documentation/accelerate) or . 

INT8 inference with `QNNPACK` might be more efficient then `fp16` but that would require non trivial changes to the code to support scale, zero_point machinery required for INT8 inference.

**Comment by trangtv57** [comment]
hi @vineelpratap,
I have same question with bill, so as you say, if we need use wav2letter in mobille. We need remove the dependency on fbgemm and use difference backend like xnnpackk or accelrerate. 
Can you give more detail about how we remove this dependency. I understand we just need build xnnpack instead of fbgemm,  and wav2letter will automatic pick new backend, or we need more changes in code and build script.
Thankyou.

**Comment by vineelpratap** [comment]
Hi, 
 Apart changing the build script, you would alsso have to remove the `fbgemm` function calls that we use in the code to perform matrix multiplication and replace with equivalent from `xnnpack` (or whatever library being used).

**Comment by trangtv57** [comment]
thanks youu @vineelpratap
