### ISSUE TITLE
Wav2letter support Window OS?

### ISSUE THREAD

**Issue by sooftware** [facebookresearch/wav2letter#831]
Wav2letter support Window OS??

**Comment by sooftware** [comment]
If limit to python binding

**Comment by padentomasello** [comment]
Hi @sooftware, unfortunately we do not currently support building in Windows OS and it is not in our roadmap for the near future. You _may_ be able to get things working by running a linux docker container on a windows host, but from a quick glance https://stackoverflow.com/questions/49589229/is-gpu-pass-through-possible-with-docker-for-windows, it appears that you would not be able to run on the GPU since nvidia-docker is only supported on linux machines.

**Comment by sooftware** [comment]
Thank you for let me know !!
