### ISSUE TITLE
Degrading accuracy in the inference mode

### ISSUE THREAD

**Issue by tetiana-myronivska** [facebookresearch/wav2letter#885]
### Question

I noticed that the recognition accuracy in the [inference mode](https://github.com/facebookresearch/wav2letter/blob/v0.2/inference/inference/examples/SimpleStreamingASRExample.cpp) is lower than in the decode mode (i.e., when running model evaluation). In the inference mode, it mainly struggles on the chunk boundary, which makes me think that the previous context is not being taken into account.

Could you please help me understand if this is the case, and, if so, what changes are needed in order to achieve accuracy in the decoding mode?

**Comment by vineelpratap** [comment]
Hi, 
You can remove the call to pruning here `https://github.com/facebookresearch/wav2letter/blob/v0.2/inference/inference/examples/AudioToWords.cpp#L105` to produce similar results as running decoder offline. 

However, note that if your audio is long (in the order of hours) pruning at regular intervals is necessary so that the process doesn't go OOM.

**Comment by tetiana-myronivska** [comment]
That solved the issue. Thank you, @vineelpratap !
