### ISSUE TITLE
Python inference to convert wav to text

### ISSUE THREAD

**Issue by AlexandrWh** [facebookresearch/wav2letter#944]
Hi,
I've built [python bindings](https://github.com/facebookresearch/wav2letter/wiki/Building-Python-bindings)
And now I'm interested in, how to make inference from wav to text
This [tutorial](https://github.com/facebookresearch/wav2letter/wiki/Python-bindings) doesn't give me usefull information
I need python script, which reads .wav file and prints recognized text using **wav2letter** library

**Comment by tlikhomanenko** [comment]
Python bindings supports only featurization and beam-search decoding where predictions from the network are provided. So that people who trained acoustic models with tensorflow/pytorch could reuse beam-search decoding from python. 

Wav2letter is c++ and models trained with it can be used for inference with Decode.cpp binary.

Here we have [colab](https://colab.research.google.com/github/facebookresearch/flashlight/blob/master/flashlight/app/asr/tutorial/notebooks/InferenceAndAlignmentCTC.ipynb) example (all tutorials are [here](https://github.com/facebookresearch/flashlight/tree/master/flashlight/app/asr/tutorial)) with recent codebase how one can do inference with the CTC acoustic model and some n-gram language model. So this is binary call with interactive regime, so that you can pass path to audio and transcription will be printed on the screen, and so on.
